title: Dataview serializer
description: Documentation for the Dataview serializer Obsidian plugin.
url: https://dsebastien.github.io
baseurl: /obsidian-dataview-serializer

remote_theme: just-the-docs/just-the-docs

plugins:
    - jekyll-remote-theme

aux_links:
    GitHub: https://github.com/dsebastien/obsidian-dataview-serializer

search_enabled: true
search:
    heading_level: 3
    previews: 2
    preview_words_before: 5
    preview_words_after: 10

heading_anchors: true
color_scheme: light

exclude:
    - SUMMARY.md
